-- =========================================================================
-- Notifiche di prossimità (vedi NotificheService): zone salvate, preferenze, sottoscrizioni
-- Web Push e storico degli avvisi mostrato nella campanella.
-- =========================================================================

-- Zone in cui l'utente vuole essere avvisato (es. Casa, Lavoro): al massimo 5 per utente.
CREATE TABLE zona_notifica (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utente_id       BIGINT NOT NULL REFERENCES utente(id) ON DELETE CASCADE,
    nome            VARCHAR(40) NOT NULL,
    posizione       geography(Point, 4326) NOT NULL,
    raggio_metri    INTEGER NOT NULL,
    data_creazione  TIMESTAMP NOT NULL DEFAULT now(),
    CONSTRAINT ck_zona_notifica_raggio CHECK (raggio_metri BETWEEN 200 AND 5000)
);
CREATE INDEX idx_zona_notifica_utente ON zona_notifica (utente_id);
CREATE INDEX idx_zona_notifica_posizione ON zona_notifica USING GIST (posizione);

-- Preferenze: il raggio ora è della zona; "solo categorie preferite" diventa un elenco esplicito.
ALTER TABLE preferenze_notifica DROP COLUMN raggio_notifica_metri;
ALTER TABLE preferenze_notifica DROP COLUMN notifiche_solo_categorie_preferite;
ALTER TABLE preferenze_notifica ADD COLUMN gravita_minima INTEGER NOT NULL DEFAULT 3;
ALTER TABLE preferenze_notifica ADD CONSTRAINT ck_preferenze_notifica_gravita CHECK (gravita_minima BETWEEN 1 AND 3);
-- Ore di silenzio (ora italiana); NULL = nessuna. Possono scavalcare la mezzanotte (es. 23-7).
ALTER TABLE preferenze_notifica ADD COLUMN ore_silenzio_da TIME;
ALTER TABLE preferenze_notifica ADD COLUMN ore_silenzio_a TIME;
ALTER TABLE preferenze_notifica ADD COLUMN gravi_in_silenzio BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE preferenze_notifica ADD COLUMN aggiornamenti_mie BOOLEAN NOT NULL DEFAULT TRUE;

-- Categorie scelte: nessuna riga = tutte quelle con gravità sufficiente.
CREATE TABLE preferenze_notifica_categoria (
    preferenze_id  BIGINT NOT NULL REFERENCES preferenze_notifica(id) ON DELETE CASCADE,
    categoria_id   BIGINT NOT NULL REFERENCES categoria(id) ON DELETE CASCADE,
    PRIMARY KEY (preferenze_id, categoria_id)
);

-- Device token -> sottoscrizione Web Push: token = endpoint del servizio push del browser,
-- più le chiavi per cifrare il contenuto (RFC 8291) e la lingua per scriverne il testo.
-- I token registrati prima non hanno chiavi: non servono a nulla.
DELETE FROM device_token;
ALTER TABLE device_token ALTER COLUMN token TYPE VARCHAR(1000);
ALTER TABLE device_token ADD COLUMN p256dh VARCHAR(200) NOT NULL;
ALTER TABLE device_token ADD COLUMN auth VARCHAR(100) NOT NULL;
ALTER TABLE device_token ADD COLUMN lingua VARCHAR(10) NOT NULL DEFAULT 'it';

-- Avvisi ricevuti (campanella). Il testo lo compone il client nella lingua attiva.
CREATE TABLE notifica (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utente_id        BIGINT NOT NULL REFERENCES utente(id) ON DELETE CASCADE,
    tipo             VARCHAR(20) NOT NULL,
    segnalazione_id  BIGINT NOT NULL REFERENCES segnalazione(id) ON DELETE CASCADE,
    zona_nome        VARCHAR(40),
    data_creazione   TIMESTAMP NOT NULL DEFAULT now(),
    letta            BOOLEAN NOT NULL DEFAULT FALSE,
    inviata_push     BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT ck_notifica_tipo CHECK (tipo IN ('VICINA', 'CONFERMATA', 'CHIUSA', 'RIMOSSA', 'SOSPESA'))
);
CREATE INDEX idx_notifica_utente_data ON notifica (utente_id, data_creazione DESC);
CREATE INDEX idx_notifica_non_lette ON notifica (utente_id) WHERE NOT letta;
CREATE INDEX idx_notifica_segnalazione ON notifica (segnalazione_id);
