-- Estensione PostGIS (idempotente: l'immagine postgis/postgis di solito la crea già al boot).
CREATE EXTENSION IF NOT EXISTS postgis;

-- =========================================================================
-- utente
-- =========================================================================
CREATE TABLE utente (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome                 VARCHAR(100)  NOT NULL,
    cognome              VARCHAR(100)  NOT NULL,
    email                VARCHAR(255)  NOT NULL,
    password_hash        TEXT          NOT NULL,
    identita_verificata  BOOLEAN       NOT NULL DEFAULT FALSE,
    punteggio_fiducia    INTEGER       NOT NULL DEFAULT 100,
    attivo               BOOLEAN       NOT NULL DEFAULT TRUE,
    data_registrazione   TIMESTAMP     NOT NULL DEFAULT now(),
    data_aggiornamento   TIMESTAMP
);

CREATE UNIQUE INDEX idx_utente_email ON utente (email);

-- =========================================================================
-- categoria (tabella, non enum: taxonomy configurabile dall'admin senza redeploy)
-- =========================================================================
CREATE TABLE categoria (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome                  VARCHAR(100) NOT NULL,
    descrizione           VARCHAR(500),
    icona                 VARCHAR(50),
    durata_validita_ore   INTEGER      NOT NULL,
    attiva                BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_categoria_nome UNIQUE (nome)
);

-- =========================================================================
-- segnalazione
-- =========================================================================
CREATE TABLE segnalazione (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    autore_id       BIGINT        NOT NULL REFERENCES utente(id),
    categoria_id    BIGINT        NOT NULL REFERENCES categoria(id),
    descrizione     VARCHAR(2000) NOT NULL,
    posizione       geography(Point, 4326) NOT NULL,
    anonima         BOOLEAN       NOT NULL DEFAULT FALSE,
    stato           VARCHAR(20)   NOT NULL DEFAULT 'ATTIVA',
    data_creazione  TIMESTAMP     NOT NULL DEFAULT now(),
    data_scadenza   TIMESTAMP     NOT NULL,
    data_rimozione  TIMESTAMP,
    CONSTRAINT ck_segnalazione_stato CHECK (stato IN ('ATTIVA', 'SCADUTA', 'SOSPESA', 'RIMOSSA'))
);

CREATE INDEX idx_segnalazione_stato ON segnalazione (stato);
CREATE INDEX idx_segnalazione_data_scadenza ON segnalazione (data_scadenza);
CREATE INDEX idx_segnalazione_autore ON segnalazione (autore_id);
CREATE INDEX idx_segnalazione_categoria ON segnalazione (categoria_id);
-- Indice spaziale per query di prossimità efficienti (ST_DWithin).
CREATE INDEX idx_segnalazione_posizione ON segnalazione USING GIST (posizione);

-- =========================================================================
-- segnalazione_abuso (un abuso per utente per segnalazione)
-- =========================================================================
CREATE TABLE segnalazione_abuso (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    segnalazione_id    BIGINT       NOT NULL REFERENCES segnalazione(id),
    utente_id          BIGINT       NOT NULL REFERENCES utente(id),
    motivo             VARCHAR(500) NOT NULL,
    data_segnalazione  TIMESTAMP    NOT NULL DEFAULT now(),
    CONSTRAINT uk_abuso_segnalazione_utente UNIQUE (segnalazione_id, utente_id)
);

CREATE INDEX idx_segnalazione_abuso_segnalazione ON segnalazione_abuso (segnalazione_id);

-- =========================================================================
-- evento_moderazione (audit trail delle transizioni di stato)
-- =========================================================================
CREATE TABLE evento_moderazione (
    id                  BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    segnalazione_id     BIGINT       NOT NULL REFERENCES segnalazione(id),
    stato_precedente    VARCHAR(20)  NOT NULL,
    stato_nuovo         VARCHAR(20)  NOT NULL,
    tipo_attore         VARCHAR(20)  NOT NULL,
    amministratore_id   BIGINT       REFERENCES utente(id),
    motivazione         VARCHAR(500),
    data_evento         TIMESTAMP    NOT NULL DEFAULT now(),
    CONSTRAINT ck_evento_moderazione_tipo_attore CHECK (tipo_attore IN ('SISTEMA', 'AUTORE', 'ADMIN'))
);

CREATE INDEX idx_evento_moderazione_segnalazione ON evento_moderazione (segnalazione_id);

-- =========================================================================
-- preferenze_notifica (1:1 con utente)
-- =========================================================================
CREATE TABLE preferenze_notifica (
    id                                     BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utente_id                              BIGINT  NOT NULL REFERENCES utente(id),
    raggio_notifica_metri                  INTEGER NOT NULL DEFAULT 1000,
    notifiche_attive                       BOOLEAN NOT NULL DEFAULT TRUE,
    notifiche_solo_categorie_preferite     BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_preferenze_notifica_utente UNIQUE (utente_id)
);

-- =========================================================================
-- device_token
-- =========================================================================
CREATE TABLE device_token (
    id                   BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utente_id            BIGINT       NOT NULL REFERENCES utente(id),
    token                VARCHAR(500) NOT NULL,
    piattaforma          VARCHAR(20)  NOT NULL,
    data_registrazione   TIMESTAMP    NOT NULL DEFAULT now(),
    ultimo_utilizzo      TIMESTAMP,
    CONSTRAINT uk_device_token_token UNIQUE (token),
    CONSTRAINT ck_device_token_piattaforma CHECK (piattaforma IN ('ANDROID', 'IOS', 'WEB'))
);

CREATE INDEX idx_device_token_utente ON device_token (utente_id);
