-- =========================================================================
-- conferma_segnalazione ("È ancora in atto?": un voto per utente per segnalazione, modificabile)
-- =========================================================================
CREATE TABLE conferma_segnalazione (
    id                BIGINT    GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    segnalazione_id   BIGINT    NOT NULL REFERENCES segnalazione(id),
    utente_id         BIGINT    NOT NULL REFERENCES utente(id),
    ancora_in_atto    BOOLEAN   NOT NULL,
    data_voto         TIMESTAMP NOT NULL DEFAULT now(),
    CONSTRAINT uk_conferma_segnalazione_utente UNIQUE (segnalazione_id, utente_id)
);

CREATE INDEX idx_conferma_segnalazione_segnalazione ON conferma_segnalazione (segnalazione_id);

-- Istante dell'ultima conferma "ancora in atto": i voti "non più in atto" contano solo se successivi.
ALTER TABLE segnalazione ADD COLUMN data_ultima_conferma TIMESTAMP;
